### ISSUE TITLE
Cannot find module 'vsts-task-lib/task' on VSTS

### ISSUE THREAD

**Issue by sdargaud** [matthid/Paket.TeamBuildCredentials#1]
Hi,

After getting the F# Helpers for VSTS form the Marketplace, I could add the "Setup paket credential manager" task to my build.
However the task is failing with "Error: Cannot find module 'vsts-task-lib/task'" as if the node_modules folder was empty.
If I download the vsix from the Releases, I can see that the node modules folder is not empty.
Is it supposed to work by downloading the F# Helpers for VSTS from the marketplace or am I doing something wrong ? (i.e. not uploading the vsix from release).

Thanks

**Comment by matthid** [comment]
Moving to https://github.com/isaacabraham/vsts-fsharp/issues/8

**Comment by sdargaud** [comment]
Thanks!
